# Generated by Django 2.1.3 on 2018-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20181121_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='initial_data'),
            preserve_default=False,
        ),
    ]
