# Generated by Django 2.1.3 on 2018-11-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
